# output "my_id" {
#   value = data.aws_vpc.default.id
# }

# output "alb-sg" {
#   value = aws_security_group.alb-sg.id
# }

# output "ssh_key" {
#   description = "ssh key generated by terraform"
#   value       = tls_private_key.sskey.private_key_pem
#   sensitive   = true
# }

output "public_ip" {
value = "${join(",", aws_instance.ss-instance-.*.public_ip)}"
}

output "alb-dns" {
  description = "Use this DNS to access the Webpage."
  value = aws_alb.ss-alb.dns_name
}