variable "region" {
  type        = string
  description = "AWS Region the instance is launched"
  default     = "us-east-1"
}
variable "generated_key_pair" {
  type        = string
  description = "Key-pair generated by Terraform"
  default     = "terraform-key-pair"
}

variable "availability_zones" {
  type        = list(string)
  description = "List of availability zones"
}

variable "instance_count" {
  type = number
  description = "No of instances to provision"
  default = 2
}

variable "myip" {
  type = list(string)
  description = "This will be your public ip"
}

variable "instance_type" {
  default = "t2.micro"
  description = "Instance type to provision"
}
variable "http_port" {
  type = number
  description = "Port for ALB Security group to allow ingress"
  default = 80
}

variable "ssh_port" {
  type = number
  description = "Port for EC2 Security group to allow ingress"
  default = 22
}

variable "http_protocol" {
  type = string
  description = "This will be the ALB listener protocol, HTTP/HTTPS"
  default = "HTTP"
}

variable "appname" {
  type = string
  description = "TThis will be used in tags name resources"
  default = ""
}