variable "region" {
  type        = string
  description = "AWS Region the instance is launched"
  default     = ""
}
variable "generated_key_pair" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "availability_zones" {
  type        = list(string)
  description = "List of availability zones"
}

variable "instance_count" {
  default = "2"
}

variable "myip" {
  type = list(string)
}

variable "instance_type" {
  default = "t2.micro"
}
variable "http_port" {
  default = 80
}

variable "ssh_port" {
  default = 22
}